import { jsPDF } from 'jspdf'

import type { Customer, Payment, UdhaarEntry } from '../core/types'
import { formatCurrency, formatDate } from './utils'

const APP_NAME = 'Digital Khata'

const TEAL: [number, number, number] = [15, 118, 110]
const INK: [number, number, number] = [23, 33, 31]
const MUTED: [number, number, number] = [110, 122, 119]
const HAIRLINE: [number, number, number] = [227, 238, 231]

/**
 * Thermal-style 80mm receipts, rendered from live application data only.
 * jsPDF's built-in fonts cannot shape Urdu script, so receipts use English
 * labels regardless of the UI language.
 */

function receiptNumber(id: string): string {
  const clean = id.replace(/[^a-zA-Z0-9]/g, '').toUpperCase()
  return `RCP-${clean.slice(0, 8).padEnd(8, 'X')}`
}

function newDoc(): { doc: jsPDF; width: number; margin: number } {
  const doc = new jsPDF({ unit: 'mm', format: [80, 150], orientation: 'portrait' })
  return { doc, width: 80, margin: 6 }
}

function divider(doc: jsPDF, y: number, width: number, margin: number): number {
  doc.setDrawColor(...HAIRLINE)
  doc.setLineWidth(0.3)
  doc.line(margin, y, width - margin, y)
  return y + 4
}

function header(doc: jsPDF, width: number, margin: number, kindLabel: string): number {
  let y = 13
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.setTextColor(...TEAL)
  doc.text(APP_NAME, width / 2, y, { align: 'center' })

  y += 5
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7.5)
  doc.setTextColor(...MUTED)
  doc.text('Smart Business Ledger', width / 2, y, { align: 'center' })

  y += 7
  doc.setFillColor(...TEAL)
  doc.roundedRect(margin, y - 4.5, width - margin * 2, 7, 1.5, 1.5, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(255, 255, 255)
  doc.text(kindLabel, width / 2, y, { align: 'center' })

  return y + 6
}

function keyValues(
  doc: jsPDF,
  y: number,
  width: number,
  margin: number,
  rows: [string, string][],
): number {
  doc.setFontSize(8)
  let cursor = y
  for (const [label, value] of rows) {
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...MUTED)
    doc.text(label, margin, cursor)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...INK)
    doc.text(value, width - margin, cursor, { align: 'right' })
    cursor += 5
  }
  return cursor
}

function amountBlock(doc: jsPDF, y: number, width: number, amount: number): number {
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...MUTED)
  doc.text('AMOUNT', width / 2, y, { align: 'center' })
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(15)
  doc.setTextColor(...TEAL)
  doc.text(formatCurrency(amount), width / 2, y + 7, { align: 'center' })
  return y + 12
}

function footer(doc: jsPDF, y: number, width: number): number {
  let cursor = y
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(...INK)
  doc.text('Thank you! / Shukriya!', width / 2, cursor, { align: 'center' })
  cursor += 5
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.setTextColor(...MUTED)
  doc.text(`Generated by ${APP_NAME}`, width / 2, cursor, { align: 'center' })
  return cursor + 4
}

function save(doc: jsPDF, number: string): void {
  doc.save(`receipt-${number.toLowerCase()}.pdf`)
}

export function downloadPaymentReceipt(
  payment: Payment,
  customer: Customer | undefined,
  customerOutstanding: number,
  linkedDescription?: string,
): void {
  const { doc, width, margin } = newDoc()
  const number = receiptNumber(payment.id)

  let y = header(doc, width, margin, 'PAYMENT RECEIPT')
  y = keyValues(doc, y, width, margin, [
    ['Receipt #', number],
    ['Date', formatDate(payment.createdAt ?? payment.date)],
    ['Customer', customer?.name ?? '-'],
    ['Phone', customer?.phone ?? '-'],
  ])
  y = divider(doc, y, width, margin)
  y = keyValues(doc, y, width, margin, [
    ['Transaction', 'Payment Received'],
    ['Method', payment.method],
    ['Description', linkedDescription ?? '-'],
  ])
  y = divider(doc, y, width, margin)
  y = amountBlock(doc, y, width, payment.amount)
  y = divider(doc, y, width, margin)
  y = keyValues(doc, y, width, margin, [
    ['Remaining Outstanding', formatCurrency(customerOutstanding)],
    ['Status', customerOutstanding === 0 ? 'SETTLED' : 'PARTIALLY PAID'],
  ])
  y = divider(doc, y, width, margin)
  footer(doc, y, width)

  save(doc, number)
}

export function downloadUdhaarReceipt(
  entry: UdhaarEntry,
  customer: Customer | undefined,
  customerOutstanding: number,
): void {
  const { doc, width, margin } = newDoc()
  const number = receiptNumber(entry.id)

  let y = header(doc, width, margin, 'UDHAAR RECEIPT')
  y = keyValues(doc, y, width, margin, [
    ['Receipt #', number],
    ['Date', formatDate(entry.createdAt)],
    ['Customer', customer?.name ?? '-'],
    ['Phone', customer?.phone ?? '-'],
  ])
  y = divider(doc, y, width, margin)
  y = keyValues(doc, y, width, margin, [
    ['Transaction', 'Udhaar (Credit)'],
    ['Description', entry.description],
    ['Due Date', entry.dueDate ? formatDate(entry.dueDate) : '-'],
  ])
  y = divider(doc, y, width, margin)
  y = amountBlock(doc, y, width, entry.remainingAmount)
  y = divider(doc, y, width, margin)
  y = keyValues(doc, y, width, margin, [
    ['Credit Amount', formatCurrency(entry.amount)],
    ['Paid', formatCurrency(entry.paidAmount)],
    ['Customer Outstanding', formatCurrency(customerOutstanding)],
  ])
  y = divider(doc, y, width, margin)
  footer(doc, y, width)

  save(doc, number)
}
