import { jsPDF } from 'jspdf'

import type { Customer, Payment, UdhaarEntry } from '../core/types'
import { formatCurrency, formatDate } from './utils'

const APP_NAME = 'Digital Khata'

const TEAL: [number, number, number] = [15, 118, 110]
const INK: [number, number, number] = [23, 33, 31]
const MUTED: [number, number, number] = [110, 122, 119]
const HAIRLINE: [number, number, number] = [227, 238, 231]

/**
 * Thermal-style 80mm receipts, rendered from live application data only.
 * jsPDF's built-in fonts cannot shape Urdu script, so receipts use English
 * labels regardless of the UI language.
 */

function receiptNumber(id: string): string {
  const clean = id.replace(/[^a-zA-Z0-9]/g, '').toUpperCase()
  return `RCP-${clean.slice(0, 8).padEnd(8, 'X')}`
}

function newDoc(): { doc: jsPDF; width: number; margin: number } {
  const doc = new jsPDF({ unit: 'mm', format: [80, 150], orientation: 'portrait' })
  return { doc, width: 80, margin: 6 }
}

function divider(doc: jsPDF, y: number, width: number, margin: number): number {
  doc.setDrawColor(...HAIRLINE)
  doc.setLineWidth(0.3)
  doc.line(margin, y, width - margin, y)
  return y + 4
}

function header(doc: jsPDF, width: number, margin: number, kindLabel: string): number {
  let y = 13
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(14)
  doc.setTextColor(...TEAL)
  doc.text(APP_NAME, width / 2, y, { align: 'center' })

  y += 5
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7.5)
  doc.setTextColor(...MUTED)
  doc.text('Smart Business Ledger', width / 2, y, { align: 'center' })

  y += 7
  doc.setFillColor(...TEAL)
  doc.roundedRect(margin, y - 4.5, width - margin * 2, 7, 1.5, 1.5, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(255, 255, 255)
  doc.text(kindLabel, width / 2, y, { align: 'center' })

  return y + 6
}

function keyValues(
  doc: jsPDF,
  y: number,
  width: number,
  margin: number,
  rows: [string, string][],
): number {
  doc.setFontSize(8)
  let cursor = y
  for (const [label, value] of rows) {
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...MUTED)
    doc.text(label, margin, cursor)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...INK)
    doc.text(value, width - margin, cursor, { align: 'right' })
    cursor += 5
  }
  return cursor
}

function amountBlock(doc: jsPDF, y: number, width: number, amount: number): number {
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...MUTED)
  doc.text('AMOUNT', width / 2, y, { align: 'center' })
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(15)
  doc.setTextColor(...TEAL)
  doc.text(formatCurrency(amount), width / 2, y + 7, { align: 'center' })
  return y + 12
}

function footer(doc: jsPDF, y: number, width: number): number {
  let cursor = y
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(...INK)
  doc.text('Thank you! / Shukriya!', width / 2, cursor, { align: 'center' })
  cursor += 5
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.setTextColor(...MUTED)
  doc.text(`Generated by ${APP_NAME}`, width / 2, cursor, { align: 'center' })
  return cursor + 4
}

function save(doc: jsPDF, number: string): void {
  doc.save(`receipt-${number.toLowerCase()}.pdf`)
}

function itemsBlock(
  doc: jsPDF,
  y: number,
  width: number,
  margin: number,
  items: { name: string; qty: number; rate: number; amount: number }[],
): number {
  let cursor = y
  const itemW = width - margin * 2
  const colItem = itemW * 0.42
  const colQty = itemW * 0.18

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7)
  doc.setTextColor(255, 255, 255)
  doc.setFillColor(...TEAL)
  doc.roundedRect(margin, cursor, itemW, 6, 1, 1, 'F')
  doc.text('ITEM', margin + 2, cursor + 4)
  doc.text('QTY', margin + colItem + 2, cursor + 4)
  doc.text('RATE', margin + colItem + colQty + 2, cursor + 4)
  doc.text('AMOUNT', width - margin - 2, cursor + 4, { align: 'right' })
  cursor += 7

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  for (const item of items) {
    if (cursor > 60) {
      cursor = 20
    }
    const name = item.name.length > 18 ? item.name.slice(0, 16) + '..' : item.name
    doc.setTextColor(...INK)
    doc.text(name, margin + 2, cursor)
    doc.setTextColor(...MUTED)
    doc.text(String(item.qty), margin + colItem + 2, cursor)
    doc.text(formatCurrency(item.rate), margin + colItem + colQty + 2, cursor)
    doc.setTextColor(...INK)
    doc.text(formatCurrency(item.qty * item.rate), width - margin - 2, cursor, { align: 'right' })
    cursor += 5
  }

  doc.setDrawColor(...HAIRLINE)
  doc.line(margin, cursor, width - margin, cursor)
  return cursor + 4
}

export function downloadPaymentReceipt(
  payment: Payment,
  customer: Customer | undefined,
  customerOutstanding: number,
  linkedDescription?: string,
): void {
  const { doc, width, margin } = newDoc()
  const number = receiptNumber(payment.id)

  let y = header(doc, width, margin, 'PAYMENT RECEIPT')
  y = keyValues(doc, y, width, margin, [
    ['Receipt #', number],
    ['Date', formatDate(payment.createdAt ?? payment.date)],
    ['Customer', customer?.name ?? '-'],
    ['Phone', customer?.phone ?? '-'],
  ])
  y = divider(doc, y, width, margin)
  y = keyValues(doc, y, width, margin, [
    ['Transaction', 'Payment Received'],
    ['Method', payment.method],
    ['Description', linkedDescription ?? '-'],
  ])
  y = divider(doc, y, width, margin)
  y = amountBlock(doc, y, width, payment.amount)
  y = divider(doc, y, width, margin)
  y = keyValues(doc, y, width, margin, [
    ['Remaining Outstanding', formatCurrency(customerOutstanding)],
    ['Status', customerOutstanding === 0 ? 'SETTLED' : 'PARTIALLY PAID'],
  ])
  y = divider(doc, y, width, margin)
  footer(doc, y, width)

  save(doc, number)
}

export function downloadUdhaarReceipt(
  entry: UdhaarEntry,
  customer: Customer | undefined,
  customerOutstanding: number,
): void {
  const { doc, width, margin } = newDoc()
  const number = receiptNumber(entry.id)

  let y = header(doc, width, margin, 'UDHAAR RECEIPT')
  y = keyValues(doc, y, width, margin, [
    ['Receipt #', number],
    ['Date', formatDate(entry.createdAt)],
    ['Customer', customer?.name ?? '-'],
    ['Phone', customer?.phone ?? '-'],
  ])
  y = divider(doc, y, width, margin)
  y = keyValues(doc, y, width, margin, [
    ['Transaction', 'Udhaar (Credit)'],
    ['Description', entry.description],
    ['Due Date', entry.dueDate ? formatDate(entry.dueDate) : '-'],
  ])
  y = divider(doc, y, width, margin)
  if (entry.items && entry.items.length > 0) {
    y = itemsBlock(doc, y, width, margin, entry.items)
    y = divider(doc, y, width, margin)
  }
  y = amountBlock(doc, y, width, entry.remainingAmount)
  y = divider(doc, y, width, margin)
  y = keyValues(doc, y, width, margin, [
    ['Credit Amount', formatCurrency(entry.amount)],
    ['Paid', formatCurrency(entry.paidAmount)],
    ['Customer Outstanding', formatCurrency(customerOutstanding)],
  ])
  y = divider(doc, y, width, margin)
  footer(doc, y, width)

  save(doc, number)
}

interface ReportData {
  periodLabel: string
  totalUdhaar: number
  totalPayments: number
  totalSales: number
  outstanding: number
  overdue: number
  transactionCount: number
  topCustomers: { name: string; phone?: string; amount: number }[]
  recentTransactions: { title: string; amount: number; date: string; type: string }[]
}

export function downloadReportPdf(data: ReportData): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' })
  const width = 210
  const margin = 15
  const contentWidth = width - margin * 2

  let y = 20

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.setTextColor(...TEAL)
  doc.text(APP_NAME, width / 2, y, { align: 'center' })

  y += 7
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(...MUTED)
  doc.text('Business Report', width / 2, y, { align: 'center' })

  y += 6
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(...INK)
  doc.text(`Period: ${data.periodLabel}`, width / 2, y, { align: 'center' })

  y += 4
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...MUTED)
  doc.text(`Generated: ${formatDate(new Date().toISOString())}`, width / 2, y, { align: 'center' })

  y += 8
  doc.setDrawColor(...HAIRLINE)
  doc.setLineWidth(0.4)
  doc.line(margin, y, width - margin, y)
  y += 8

  const statBoxes: [string, string][] = [
    ['Total Udhaar', formatCurrency(data.totalUdhaar)],
    ['Total Payments', formatCurrency(data.totalPayments)],
    ['Total Sales', formatCurrency(data.totalSales)],
    ['Outstanding', formatCurrency(data.outstanding)],
    ['Overdue', formatCurrency(data.overdue)],
    ['Transactions', String(data.transactionCount)],
  ]

  const boxW = (contentWidth - 10) / 3
  const boxH = 22
  for (let i = 0; i < statBoxes.length; i++) {
    const col = i % 3
    const row = Math.floor(i / 3)
    const bx = margin + col * (boxW + 5)
    const by = y + row * (boxH + 4)

    doc.setFillColor(250, 252, 250)
    doc.setDrawColor(...HAIRLINE)
    doc.roundedRect(bx, by, boxW, boxH, 2, 2, 'FD')

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    doc.setTextColor(...MUTED)
    doc.text(statBoxes[i][0], bx + 4, by + 8)

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(...TEAL)
    doc.text(statBoxes[i][1], bx + 4, by + 16)
  }

  y += Math.ceil(statBoxes.length / 3) * (boxH + 4) + 6

  if (data.topCustomers.length > 0) {
    doc.setDrawColor(...HAIRLINE)
    doc.line(margin, y, width - margin, y)
    y += 6

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.setTextColor(...INK)
    doc.text('Top Customers by Outstanding', margin, y)
    y += 6

    doc.setFillColor(...TEAL)
    doc.roundedRect(margin, y, contentWidth, 7, 0, 0, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.setTextColor(255, 255, 255)
    doc.text('#', margin + 4, y + 5)
    doc.text('Customer', margin + 14, y + 5)
    doc.text('Phone', margin + 90, y + 5)
    doc.text('Outstanding', width - margin - 4, y + 5, { align: 'right' })
    y += 9

    doc.setFontSize(8)
    for (let i = 0; i < data.topCustomers.length; i++) {
      const c = data.topCustomers[i]
      const isEven = i % 2 === 0
      if (isEven) {
        doc.setFillColor(247, 250, 247)
        doc.rect(margin, y - 4, contentWidth, 7, 'F')
      }
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...MUTED)
      doc.text(`${i + 1}`, margin + 4, y)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...INK)
      doc.text(c.name, margin + 14, y)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...MUTED)
      doc.text(c.phone ?? '-', margin + 90, y)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(220, 38, 38)
      doc.text(formatCurrency(c.amount), width - margin - 4, y, { align: 'right' })
      y += 7
    }
    y += 4
  }

  if (data.recentTransactions.length > 0) {
    if (y > 250) {
      doc.addPage()
      y = 20
    }

    doc.setDrawColor(...HAIRLINE)
    doc.line(margin, y, width - margin, y)
    y += 6

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.setTextColor(...INK)
    doc.text('Recent Transactions', margin, y)
    y += 6

    doc.setFillColor(...TEAL)
    doc.roundedRect(margin, y, contentWidth, 7, 0, 0, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.setTextColor(255, 255, 255)
    doc.text('Date', margin + 4, y + 5)
    doc.text('Description', margin + 35, y + 5)
    doc.text('Type', margin + 120, y + 5)
    doc.text('Amount', width - margin - 4, y + 5, { align: 'right' })
    y += 9

    doc.setFontSize(8)
    for (let i = 0; i < data.recentTransactions.length; i++) {
      const tx = data.recentTransactions[i]
      if (y > 280) {
        doc.addPage()
        y = 20
      }
      const isEven = i % 2 === 0
      if (isEven) {
        doc.setFillColor(247, 250, 247)
        doc.rect(margin, y - 4, contentWidth, 7, 'F')
      }
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...MUTED)
      doc.text(formatDate(tx.date), margin + 4, y)
      doc.setTextColor(...INK)
      const desc = tx.title.length > 40 ? tx.title.slice(0, 38) + '...' : tx.title
      doc.text(desc, margin + 35, y)
      doc.setTextColor(...MUTED)
      doc.text(tx.type, margin + 120, y)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(tx.type === 'payment' ? 15 : 23, tx.type === 'payment' ? 118 : 33, tx.type === 'payment' ? 110 : 31)
      doc.text(formatCurrency(tx.amount), width - margin - 4, y, { align: 'right' })
      y += 7
    }
  }

  y += 8
  doc.setDrawColor(...HAIRLINE)
  doc.line(margin, y, width - margin, y)
  y += 6
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(...INK)
  doc.text('Thank you for using Digital Khata!', width / 2, y, { align: 'center' })
  y += 5
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.setTextColor(...MUTED)
  doc.text(`Generated by ${APP_NAME} — Smart Business Ledger`, width / 2, y, { align: 'center' })

  doc.save(`report-${data.periodLabel.toLowerCase().replace(/\s+/g, '-')}.pdf`)
}

interface TopItemRow {
  name: string
  qty: number
  revenue: number
  sales: number
}

interface TopItemsReportData {
  periodLabel: string
  totalRevenue: number
  totalQty: number
  itemCount: number
  items: TopItemRow[]
}

export function downloadTopItemsPdf(data: TopItemsReportData): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' })
  const width = 210
  const margin = 15
  const contentWidth = width - margin * 2

  let y = 20

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.setTextColor(...TEAL)
  doc.text(APP_NAME, width / 2, y, { align: 'center' })

  y += 7
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(...MUTED)
  doc.text('Top Selling Items Report', width / 2, y, { align: 'center' })

  y += 6
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(...INK)
  doc.text(`Period: ${data.periodLabel}`, width / 2, y, { align: 'center' })

  y += 4
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...MUTED)
  doc.text(`Generated: ${formatDate(new Date().toISOString())}`, width / 2, y, { align: 'center' })

  y += 8
  doc.setDrawColor(...HAIRLINE)
  doc.setLineWidth(0.4)
  doc.line(margin, y, width - margin, y)
  y += 8

  const statBoxes: [string, string][] = [
    ['Items Sold', String(data.itemCount)],
    ['Total Quantity', String(data.totalQty)],
    ['Total Revenue', formatCurrency(data.totalRevenue)],
  ]

  const boxW = (contentWidth - 10) / 3
  const boxH = 22
  for (let i = 0; i < statBoxes.length; i++) {
    const bx = margin + i * (boxW + 5)
    doc.setFillColor(250, 252, 250)
    doc.setDrawColor(...HAIRLINE)
    doc.roundedRect(bx, y, boxW, boxH, 2, 2, 'FD')
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    doc.setTextColor(...MUTED)
    doc.text(statBoxes[i][0], bx + 4, y + 8)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(...TEAL)
    doc.text(statBoxes[i][1], bx + 4, y + 16)
  }
  y += boxH + 10

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(...INK)
  doc.text('Item Details', margin, y)
  y += 6

  doc.setFillColor(...TEAL)
  doc.roundedRect(margin, y, contentWidth, 7, 0, 0, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(255, 255, 255)
  doc.text('#', margin + 4, y + 5)
  doc.text('Item', margin + 14, y + 5)
  doc.text('Qty', margin + 110, y + 5)
  doc.text('Sales', margin + 135, y + 5)
  doc.text('Revenue', width - margin - 4, y + 5, { align: 'right' })
  y += 9

  doc.setFontSize(8)
  data.items.forEach((item, i) => {
    if (y > 280) {
      doc.addPage()
      y = 20
      doc.setFillColor(...TEAL)
      doc.roundedRect(margin, y, contentWidth, 7, 0, 0, 'F')
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(8)
      doc.setTextColor(255, 255, 255)
      doc.text('#', margin + 4, y + 5)
      doc.text('Item', margin + 14, y + 5)
      doc.text('Qty', margin + 110, y + 5)
      doc.text('Sales', margin + 135, y + 5)
      doc.text('Revenue', width - margin - 4, y + 5, { align: 'right' })
      y += 9
    }
    const isEven = i % 2 === 0
    if (isEven) {
      doc.setFillColor(247, 250, 247)
      doc.rect(margin, y - 4, contentWidth, 7, 'F')
    }
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...MUTED)
    doc.text(`${i + 1}`, margin + 4, y)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...INK)
    const name = item.name.length > 28 ? item.name.slice(0, 26) + '..' : item.name
    doc.text(name, margin + 14, y)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(15, 118, 110)
    doc.text(String(item.qty), margin + 110, y)
    doc.setTextColor(...MUTED)
    doc.text(String(item.sales), margin + 135, y)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...INK)
    doc.text(formatCurrency(item.revenue), width - margin - 4, y, { align: 'right' })
    y += 7
  })

  y += 8
  doc.setDrawColor(...HAIRLINE)
  doc.line(margin, y, width - margin, y)
  y += 6
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(...INK)
  doc.text('Thank you for using Digital Khata!', width / 2, y, { align: 'center' })
  y += 5
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.setTextColor(...MUTED)
  doc.text(`Generated by ${APP_NAME} — Smart Business Ledger`, width / 2, y, { align: 'center' })

  doc.save(`top-items-${data.periodLabel.toLowerCase().replace(/\s+/g, '-')}.pdf`)
}

interface ProductPdfRow {
  name: string
  rate: number
  cost?: number
  stock?: number
  margin: number | null
}

interface ProductsPdfData {
  generatedLabel: string
  totalProducts: number
  totalStock: number
  lowStock: number
  totalInvestment: number
  stockValue: number
  potentialProfit: number
  soldRevenue: number
  soldCost: number
  soldProfit: number
  stockOnlyProducts: number
  products: ProductPdfRow[]
}

export function downloadProductsPdf(data: ProductsPdfData): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' })
  const width = 210
  const metric = 14
  const contentWidth = width - metric * 2

  const GREEN: [number, number, number] = [22, 160, 133]
  const AMBER: [number, number, number] = [217, 119, 6]

  let page = 1

  const drawFrame = () => {
    doc.setDrawColor(...HAIRLINE)
    doc.setLineWidth(0.35)
    doc.rect(metric, 8, contentWidth, 272, 'S')
  }

  const drawBanner = (y: number): number => {
    doc.setFillColor(16, 116, 105)
    doc.roundedRect(metric, y, contentWidth, 27, 4, 4, 'F')
    doc.setFillColor(...GREEN)
    doc.rect(metric, y + 27, contentWidth, 1.4, 'F')

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(19)
    doc.setTextColor(255, 255, 255)
    doc.text(APP_NAME, width / 2, y + 11, { align: 'center' })

    doc.setFontSize(11)
    doc.setTextColor(218, 246, 238)
    doc.text('Products & Profit Report', width / 2, y + 18, { align: 'center' })

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(205, 232, 222)
    doc.text(`Generated: ${data.generatedLabel}`, width / 2, y + 23.5, { align: 'center' })

    drawFrame()
    return y + 27 + 8
  }

  const drawFooter = () => {
    doc.setDrawColor(...HAIRLINE)
    doc.setLineWidth(0.25)
    doc.line(metric, 286, width - metric, 286)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7.5)
    doc.setTextColor(...MUTED)
    doc.text(`${APP_NAME} — Smart Business Ledger`, metric, 291)
    doc.setFont('helvetica', 'bold')
    doc.text(`Page ${page}`, width - metric, 291, { align: 'right' })
  }

  const statBox = (bx: number, by: number, boxW: number, boxH: number, label: string, value: string, accent: [number, number, number], valueColor?: [number, number, number]) => {
    doc.setFillColor(250, 252, 250)
    doc.setDrawColor(...HAIRLINE)
    doc.roundedRect(bx, by, boxW, boxH, 3, 3, 'FD')
    doc.setFillColor(...accent)
    doc.rect(bx, by, 1.6, boxH, 'F')
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    doc.setTextColor(...MUTED)
    doc.text(label.toUpperCase(), bx + 6, by + 8)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(...(valueColor ?? TEAL))
    doc.text(value, bx + 6, by + 16.5)
  }

  const sectionTitle = (title: string): number => {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12.5)
    doc.setTextColor(...INK)
    doc.text(title, metric, y)
    doc.setFillColor(...GREEN)
    doc.rect(metric, y + 1.5, 14, 0.8, 'F')
    return y + 7
  }

  let y = drawBanner(10)

  const summary: [string, string, [number, number, number], [number, number, number]][] = [
    ['Products', String(data.totalProducts), TEAL, INK],
    ['Total Stock', String(data.totalStock), TEAL, INK],
    ['Low Stock', String(data.lowStock), AMBER, INK],
    ['Investment', formatCurrency(data.totalInvestment), TEAL, INK],
    ['Stock Value', formatCurrency(data.stockValue), TEAL, INK],
    [data.potentialProfit >= 0 ? 'Potential Profit' : 'Potential Loss', formatCurrency(data.potentialProfit), data.potentialProfit >= 0 ? GREEN : [220, 38, 38], data.potentialProfit >= 0 ? [15, 118, 110] : [220, 38, 38]],
  ]

  const boxW = (contentWidth - 12) / 3
  const boxH = 24
  for (let i = 0; i < summary.length; i++) {
    const col = i % 3
    const row = Math.floor(i / 3)
    statBox(metric + col * (boxW + 6), y + row * (boxH + 5), boxW, boxH, summary[i][0], summary[i][1], summary[i][2], summary[i][3] as [number, number, number])
  }
  y += 2 * (boxH + 5) + 10

  if (data.stockOnlyProducts > 0) {
    y = sectionTitle('Profit From Sales')
    const sold: [string, string, [number, number, number]][] = [
      ['Sold Revenue', formatCurrency(data.soldRevenue), TEAL],
      ['Cost of Goods Sold', formatCurrency(data.soldCost), TEAL],
      [data.soldProfit >= 0 ? 'Profit' : 'Loss', formatCurrency(data.soldProfit), data.soldProfit >= 0 ? GREEN : [220, 38, 38]],
    ]
    for (let i = 0; i < 3; i++) {
      statBox(metric + i * (boxW + 6), y, boxW, boxH, sold[i][0], sold[i][1], sold[i][2], i === 2 ? (data.soldProfit >= 0 ? (GREEN as [number, number, number]) : [220, 38, 38]) : undefined)
    }
    y += boxH + 12
  }

  y = sectionTitle('Product Details')
  doc.setFillColor(16, 116, 105)
  doc.roundedRect(metric, y, contentWidth, 8, 2, 2, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8.5)
  doc.setTextColor(255, 255, 255)
  doc.text('#', metric + 5, y + 5.5)
  doc.text('Product', metric + 14, y + 5.5)
  doc.text('Cost', metric + 78, y + 5.5)
  doc.text('Rate', metric + 100, y + 5.5)
  doc.text('Stock', metric + 122, y + 5.5)
  doc.text('Margin', width - metric - 5, y + 5.5, { align: 'right' })
  y += 10

  const drawTableHeader = () => {
    doc.setFillColor(16, 116, 105)
    doc.roundedRect(metric, y, contentWidth, 8, 2, 2, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8.5)
    doc.setTextColor(255, 255, 255)
    doc.text('#', metric + 5, y + 5.5)
    doc.text('Product', metric + 14, y + 5.5)
    doc.text('Cost', metric + 78, y + 5.5)
    doc.text('Rate', metric + 100, y + 5.5)
    doc.text('Stock', metric + 122, y + 5.5)
    doc.text('Margin', width - metric - 5, y + 5.5, { align: 'right' })
    y += 10
  }

  doc.setFontSize(8.5)
  data.products.forEach((product, i) => {
    if (y > 250) {
      doc.addPage()
      page += 1
      y = drawBanner(10)
      drawTableHeader()
    }
    const isEven = i % 2 === 0
    if (isEven) {
      doc.setFillColor(247, 250, 247)
      doc.rect(metric, y - 4.5, contentWidth, 8.5, 'F')
    }
    doc.setDrawColor(240, 245, 242)
    doc.setLineWidth(0.2)
    doc.line(metric, y + 4.5, width - metric, y + 4.5)

    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...MUTED)
    doc.text(`${i + 1}`, metric + 5, y)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...INK)
    const name = product.name.length > 20 ? product.name.slice(0, 18) + '..' : product.name
    doc.text(name, metric + 14, y)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...MUTED)
    doc.text(product.cost !== undefined ? formatCurrency(product.cost) : '-', metric + 78, y)
    doc.text(formatCurrency(product.rate), metric + 100, y)
    doc.text(product.stock !== undefined ? String(product.stock) : '-', metric + 122, y)
    doc.setFont('helvetica', 'bold')
    if (product.margin !== null) {
      const col: [number, number, number] = product.margin >= 0 ? [15, 118, 110] : [220, 38, 38]
      doc.setTextColor(...col)
      doc.text(`${product.margin >= 0 ? '+' : ''}${product.margin}%`, width - metric - 5, y, { align: 'right' })
    } else {
      doc.setTextColor(...MUTED)
      doc.text('-', width - metric - 5, y, { align: 'right' })
    }
    y += 9
  })

  y += 10
  drawFooter()
  doc.save('products-and-profit.pdf')
}

interface ReceivedReportData {
  period: 'daily' | 'weekly' | 'monthly'
  startDate: string
  totalReceived: number
  paymentCount: number
  byMethod: Record<string, number>
  topPayers: { name: string; total: number; count: number }[]
  payments: { date: string; customerName: string; amount: number; method: string }[]
}

interface StatementLine {
  date: string
  description: string
  debit: number
  credit: number
  balance: number
}

interface StatementData {
  shopName: string
  customer: Customer
  outstanding: number
  totalPaid: number
  totalSales: number
  generatedAt: string
  lines: StatementLine[]
}

/**
 * Full customer Khata statement (running balance ledger) on A4.
 * Udhaar increases the balance (credit), payments and sales reduce it.
 */
export function downloadCustomerStatementPdf(data: StatementData): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' })
  const width = 210
  const margin = 15
  const contentWidth = width - margin * 2

  let y = 20

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.setTextColor(...TEAL)
  doc.text(APP_NAME, width / 2, y, { align: 'center' })

  y += 7
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(...MUTED)
  doc.text('Customer Khata Statement', width / 2, y, { align: 'center' })

  y += 6
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  doc.setTextColor(...INK)
  doc.text(data.shopName || 'My Shop', width / 2, y, { align: 'center' })

  y += 5
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...MUTED)
  doc.text(`Generated: ${data.generatedAt}`, width / 2, y, { align: 'center' })

  y += 8
  doc.setDrawColor(...HAIRLINE)
  doc.setLineWidth(0.4)
  doc.line(margin, y, width - margin, y)
  y += 8

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.setTextColor(...INK)
  doc.text('Customer', margin, y)
  y += 6
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(...INK)
  doc.text(data.customer.name, margin, y)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(...MUTED)
  doc.text(data.customer.phone || '', margin + 80, y)
  if (data.customer.address) {
    y += 5
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.setTextColor(...MUTED)
    doc.text(data.customer.address, margin, y)
  }
  y += 8

  const summary: [string, string][] = [
    ['Outstanding Balance', formatCurrency(data.outstanding)],
    ['Total Paid', formatCurrency(data.totalPaid)],
    ['Total Sales', formatCurrency(data.totalSales)],
  ]
  const boxW = (contentWidth - 10) / 3
  const boxH = 20
  for (let i = 0; i < summary.length; i++) {
    const bx = margin + i * (boxW + 5)
    doc.setFillColor(250, 252, 250)
    doc.setDrawColor(...HAIRLINE)
    doc.roundedRect(bx, y, boxW, boxH, 2, 2, 'FD')
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    doc.setTextColor(...MUTED)
    doc.text(summary[i][0], bx + 4, y + 8)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(...TEAL)
    doc.text(summary[i][1], bx + 4, y + 16)
  }
  y += boxH + 8

  doc.setDrawColor(...HAIRLINE)
  doc.line(margin, y, width - margin, y)
  y += 6

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(...INK)
  doc.text('Statement History', margin, y)
  y += 6

  doc.setFillColor(...TEAL)
  doc.roundedRect(margin, y, contentWidth, 7, 0, 0, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(255, 255, 255)
  doc.text('Date', margin + 4, y + 5)
  doc.text('Description', margin + 30, y + 5)
  doc.text('Debit', margin + 110, y + 5)
  doc.text('Credit', margin + 132, y + 5)
  doc.text('Balance', width - margin - 4, y + 5, { align: 'right' })
  y += 9

  doc.setFontSize(8)
  for (let i = 0; i < data.lines.length; i++) {
    if (y > 280) {
      doc.addPage()
      y = 20

      doc.setFillColor(...TEAL)
      doc.roundedRect(margin, y, contentWidth, 7, 0, 0, 'F')
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(8)
      doc.setTextColor(255, 255, 255)
      doc.text('Date', margin + 4, y + 5)
      doc.text('Description', margin + 30, y + 5)
      doc.text('Debit', margin + 110, y + 5)
      doc.text('Credit', margin + 132, y + 5)
      doc.text('Balance', width - margin - 4, y + 5, { align: 'right' })
      y += 9
    }
    const line = data.lines[i]
    const isEven = i % 2 === 0
    if (isEven) {
      doc.setFillColor(247, 250, 247)
      doc.rect(margin, y - 4, contentWidth, 7, 'F')
    }
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...MUTED)
    doc.text(line.date, margin + 4, y)
    const desc = line.description.length > 26 ? line.description.slice(0, 24) + '...' : line.description
    doc.setTextColor(...INK)
    doc.text(desc, margin + 30, y)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...MUTED)
    doc.text(line.debit ? formatCurrency(line.debit) : '-', margin + 110, y)
    doc.text(line.credit ? formatCurrency(line.credit) : '-', margin + 132, y)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(line.balance >= 0 ? 220 : 15, line.balance >= 0 ? 38 : 118, line.balance >= 0 ? 38 : 110)
    doc.text(formatCurrency(line.balance), width - margin - 4, y, { align: 'right' })
    y += 7
  }

  y += 6
  doc.setDrawColor(...HAIRLINE)
  doc.line(margin, y, width - margin, y)
  y += 8

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(...INK)
  doc.text(`Closing Balance: ${formatCurrency(data.outstanding)}`, margin, y)
  y += 5

  y += 4
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...MUTED)
  doc.text('Debit = Udhaar taken (you owe nothing / added to their khata)', margin, y)
  y += 4
  doc.text('Credit = Payment received or sale that reduces the balance', margin, y)
  y += 4

  y += 2
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(...INK)
  doc.text('Thank you / Shukriya!', width / 2, y, { align: 'center' })
  y += 5
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.setTextColor(...MUTED)
  doc.text(`Generated by ${APP_NAME} — Smart Business Ledger`, width / 2, y, { align: 'center' })

  doc.save(`khata-statement-${data.customer.name.replace(/\s+/g, '-').toLowerCase()}.pdf`)
}

export function downloadReceivedReportPdf(data: ReceivedReportData): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' })
  const width = 210
  const margin = 15
  const contentWidth = width - margin * 2

  const periodLabel = data.period === 'daily' ? 'Today' : data.period === 'weekly' ? 'Last 7 Days' : 'This Month'

  let y = 20

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.setTextColor(...TEAL)
  doc.text(APP_NAME, width / 2, y, { align: 'center' })

  y += 7
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(...MUTED)
  doc.text('Payments Received Report', width / 2, y, { align: 'center' })

  y += 6
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(...INK)
  doc.text(`Period: ${periodLabel} (from ${data.startDate})`, width / 2, y, { align: 'center' })

  y += 4
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...MUTED)
  doc.text(`Generated: ${formatDate(new Date().toISOString())}`, width / 2, y, { align: 'center' })

  y += 8
  doc.setDrawColor(...HAIRLINE)
  doc.setLineWidth(0.4)
  doc.line(margin, y, width - margin, y)
  y += 8

  const summaryBoxes: [string, string][] = [
    ['Total Received', formatCurrency(data.totalReceived)],
    ['Payment Count', String(data.paymentCount)],
    ['Avg Payment', data.paymentCount > 0 ? formatCurrency(Math.round(data.totalReceived / data.paymentCount)) : formatCurrency(0)],
  ]

  const boxW = (contentWidth - 10) / 3
  const boxH = 22
  for (let i = 0; i < summaryBoxes.length; i++) {
    const bx = margin + i * (boxW + 5)
    doc.setFillColor(250, 252, 250)
    doc.setDrawColor(...HAIRLINE)
    doc.roundedRect(bx, y, boxW, boxH, 2, 2, 'FD')

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    doc.setTextColor(...MUTED)
    doc.text(summaryBoxes[i][0], bx + 4, y + 8)

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(...TEAL)
    doc.text(summaryBoxes[i][1], bx + 4, y + 16)
  }

  y += boxH + 8

  const methodEntries = Object.entries(data.byMethod)
  if (methodEntries.length > 0) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.setTextColor(...INK)
    doc.text('By Payment Method', margin, y)
    y += 6

    doc.setFontSize(8)
    for (const [method, amount] of methodEntries) {
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...MUTED)
      doc.text(method, margin + 4, y)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...INK)
      doc.text(formatCurrency(amount), width - margin - 4, y, { align: 'right' })
      y += 6
    }
    y += 4
  }

  if (data.topPayers.length > 0) {
    doc.setDrawColor(...HAIRLINE)
    doc.line(margin, y, width - margin, y)
    y += 6

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.setTextColor(...INK)
    doc.text('Top Payers', margin, y)
    y += 6

    doc.setFillColor(...TEAL)
    doc.roundedRect(margin, y, contentWidth, 7, 0, 0, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.setTextColor(255, 255, 255)
    doc.text('#', margin + 4, y + 5)
    doc.text('Customer', margin + 14, y + 5)
    doc.text('Payments', margin + 100, y + 5)
    doc.text('Total', width - margin - 4, y + 5, { align: 'right' })
    y += 9

    doc.setFontSize(8)
    for (let i = 0; i < data.topPayers.length; i++) {
      const p = data.topPayers[i]
      if (i % 2 === 0) {
        doc.setFillColor(247, 250, 247)
        doc.rect(margin, y - 4, contentWidth, 7, 'F')
      }
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...MUTED)
      doc.text(`${i + 1}`, margin + 4, y)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...INK)
      doc.text(p.name, margin + 14, y)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...MUTED)
      doc.text(String(p.count), margin + 100, y)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...TEAL)
      doc.text(formatCurrency(p.total), width - margin - 4, y, { align: 'right' })
      y += 7
    }
    y += 4
  }

  if (data.payments.length > 0) {
    if (y > 240) {
      doc.addPage()
      y = 20
    }

    doc.setDrawColor(...HAIRLINE)
    doc.line(margin, y, width - margin, y)
    y += 6

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.setTextColor(...INK)
    doc.text('Payment Details', margin, y)
    y += 6

    doc.setFillColor(...TEAL)
    doc.roundedRect(margin, y, contentWidth, 7, 0, 0, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8)
    doc.setTextColor(255, 255, 255)
    doc.text('Date', margin + 4, y + 5)
    doc.text('Customer', margin + 35, y + 5)
    doc.text('Method', margin + 120, y + 5)
    doc.text('Amount', width - margin - 4, y + 5, { align: 'right' })
    y += 9

    doc.setFontSize(8)
    for (let i = 0; i < data.payments.length; i++) {
      const p = data.payments[i]
      if (y > 280) {
        doc.addPage()
        y = 20
      }
      if (i % 2 === 0) {
        doc.setFillColor(247, 250, 247)
        doc.rect(margin, y - 4, contentWidth, 7, 'F')
      }
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...MUTED)
      doc.text(formatDate(p.date), margin + 4, y)
      doc.setTextColor(...INK)
      doc.text(p.customerName, margin + 35, y)
      doc.setTextColor(...MUTED)
      doc.text(p.method, margin + 120, y)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...TEAL)
      doc.text(formatCurrency(p.amount), width - margin - 4, y, { align: 'right' })
      y += 7
    }
  }

  y += 8
  doc.setDrawColor(...HAIRLINE)
  doc.line(margin, y, width - margin, y)
  y += 6
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(...INK)
  doc.text('Thank you for using Digital Khata!', width / 2, y, { align: 'center' })
  y += 5
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.setTextColor(...MUTED)
  doc.text(`Generated by ${APP_NAME} — Smart Business Ledger`, width / 2, y, { align: 'center' })

  doc.save(`received-report-${data.period}-${data.startDate}.pdf`)
}

interface CashBookLine {
  date: string
  description: string
  type: 'sale' | 'payment' | 'udhaar'
  amount: number
  customerName?: string
}

interface CashBookData {
  periodLabel: string
  generatedAt: string
  cashIn: number
  cashOut: number
  netCash: number
  paidIn: number
  saleIn: number
  udhaarGiven: number
  transactionCount: number
  lines: CashBookLine[]
}

/**
 * Cash Book (roz ka hisaab) report on A4 — daily cash in/out summary.
 */
export function downloadCashBookPdf(data: CashBookData): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'portrait' })
  const width = 210
  const margin = 15
  const contentWidth = width - margin * 2

  let y = 20

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.setTextColor(...TEAL)
  doc.text(APP_NAME, width / 2, y, { align: 'center' })

  y += 7
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(...MUTED)
  doc.text('Cash Book / Roz Ka Hisaab', width / 2, y, { align: 'center' })

  y += 6
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(...INK)
  doc.text(`Period: ${data.periodLabel}`, width / 2, y, { align: 'center' })

  y += 4
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(...MUTED)
  doc.text(`Generated: ${data.generatedAt}`, width / 2, y, { align: 'center' })

  y += 8
  doc.setDrawColor(...HAIRLINE)
  doc.setLineWidth(0.4)
  doc.line(margin, y, width - margin, y)
  y += 8

  const boxes: [string, string, [number, number, number]][] = [
    ['Cash In', formatCurrency(data.cashIn), [15, 118, 110]],
    ['Cash Out', formatCurrency(data.cashOut), [220, 38, 38]],
    ['Net Cash', formatCurrency(data.netCash), [15, 118, 110]],
  ]
  const boxW = (contentWidth - 10) / 3
  const boxH = 22
  for (let i = 0; i < boxes.length; i++) {
    const bx = margin + i * (boxW + 5)
    doc.setFillColor(250, 252, 250)
    doc.setDrawColor(...HAIRLINE)
    doc.roundedRect(bx, y, boxW, boxH, 2, 2, 'FD')
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(7)
    doc.setTextColor(...MUTED)
    doc.text(boxes[i][0], bx + 4, y + 8)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(11)
    doc.setTextColor(...boxes[i][2])
    doc.text(boxes[i][1], bx + 4, y + 16)
  }
  y += boxH + 8

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(...INK)
  doc.text('Breakdown', margin, y)
  y += 6
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.setTextColor(...INK)
  doc.text(`Payments Received: ${formatCurrency(data.paidIn)}`, margin, y)
  y += 5
  doc.text(`Sales: ${formatCurrency(data.saleIn)}`, margin, y)
  y += 5
  doc.text(`Udhaar Given: ${formatCurrency(data.udhaarGiven)}`, margin, y)
  y += 5
  doc.text(`Transactions: ${data.transactionCount}`, margin, y)

  y += 6
  doc.setDrawColor(...HAIRLINE)
  doc.line(margin, y, width - margin, y)
  y += 6

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.setTextColor(...INK)
  doc.text('Transaction Details', margin, y)
  y += 6

  doc.setFillColor(...TEAL)
  doc.roundedRect(margin, y, contentWidth, 7, 0, 0, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8)
  doc.setTextColor(255, 255, 255)
  doc.text('Date', margin + 4, y + 5)
  doc.text('Description', margin + 32, y + 5)
  doc.text('Type', margin + 100, y + 5)
  doc.text('Amount', width - margin - 4, y + 5, { align: 'right' })
  y += 9

  doc.setFontSize(8)
  for (let i = 0; i < data.lines.length; i++) {
    if (y > 280) {
      doc.addPage()
      y = 20
      doc.setFillColor(...TEAL)
      doc.roundedRect(margin, y, contentWidth, 7, 0, 0, 'F')
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(8)
      doc.setTextColor(255, 255, 255)
      doc.text('Date', margin + 4, y + 5)
      doc.text('Description', margin + 32, y + 5)
      doc.text('Type', margin + 100, y + 5)
      doc.text('Amount', width - margin - 4, y + 5, { align: 'right' })
      y += 9
    }
    const line = data.lines[i]
    const isEven = i % 2 === 0
    if (isEven) {
      doc.setFillColor(247, 250, 247)
      doc.rect(margin, y - 4, contentWidth, 7, 'F')
    }
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...MUTED)
    doc.text(formatDate(line.date), margin + 4, y)
    const desc = line.description.length > 30 ? line.description.slice(0, 28) + '...' : line.description
    doc.setTextColor(...INK)
    doc.text(desc, margin + 32, y)
    doc.setTextColor(...MUTED)
    doc.text(line.customerName || line.type, margin + 100, y)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(line.type === 'udhaar' ? 220 : 15, line.type === 'udhaar' ? 38 : 118, line.type === 'udhaar' ? 38 : 110)
    doc.text(
      `${line.type === 'udhaar' ? '-' : '+'}${formatCurrency(line.amount)}`,
      width - margin - 4,
      y,
      { align: 'right' },
    )
    y += 7
  }

  y += 8
  doc.setDrawColor(...HAIRLINE)
  doc.line(margin, y, width - margin, y)
  y += 6
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(...INK)
  doc.text('Thank you / Shukriya!', width / 2, y, { align: 'center' })
  y += 5
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(7)
  doc.setTextColor(...MUTED)
  doc.text(`Generated by ${APP_NAME} — Smart Business Ledger`, width / 2, y, { align: 'center' })

  doc.save(`cashbook-${data.periodLabel.toLowerCase().replace(/\s+/g, '-')}.pdf`)
}
